// This is our fake database of bus routes
export const ALL_BUSES = [
  {
    id: 1,
    name: 'Uttarakhand Raftaar',
    number: 'UA 07 1234',
    source: 'Roorkee',
    destination: 'Haridwar',
    departureTime: '5:30 AM',
    arrivalTime: '7:00 AM',
    duration: '1h 30m',
    type: 'Non-AC',
  },
  {
    id: 2,
    name: 'Doon Express',
    number: 'UP 11 5678',
    source: 'Roorkee',
    destination: 'Haridwar',
    departureTime: '6:30 AM',
    arrivalTime: '7:45 AM',
    duration: '1h 15m',
    type: 'AC',
  },
  {
    id: 3,
    name: 'Garhwal Deluxe',
    number: 'UK 08 9012',
    source: 'Roorkee',
    destination: 'Haridwar',
    departureTime: '7:15 AM',
    arrivalTime: '8:55 AM',
    duration: '1h 40m',
    type: 'Non-AC',
  },
  {
    id: 4,
    name: 'Nanda Devi AC Express',
    number: 'UA 07 4321',
    source: 'Roorkee',
    destination: 'Haridwar',
    departureTime: '8:00 AM',
    arrivalTime: '9:10 AM',
    duration: '1h 10m',
    type: 'AC',
  },
  {
    id: 5,
    name: 'Haridwar Express',
    source: 'Delhi',
    destination: 'Haridwar',
    departureTime: '9:00 AM',
    arrivalTime: '2:30 PM',
    duration: '5h 30m',
    type: 'AC',
  },
];